### ISSUE TITLE
[a11y] accessibility audit 

### ISSUE THREAD

**Issue by hshoff** [hshoff/vx#12]

**Comment by williaster** [comment]
gonna close this as there haven't been any major issues reported for ~3 years. 

generally I think vx isn't opinionated on accessibility and allows chart creators to make them accessible (`aria-label`s on `svg`s, tab-able tooltips, etc.)

**Comment by robinmetral** [comment]
Hi! I'm evaluating viz libraries for accessibility, and I'm surprised that there's little mention of this on a lib with 15k+ stars.

In response to "there haven't been any major issues reported for ~3 years" I can report that many interactive examples in the gallery[^1] would likely not pass a WCAG 2.1 audit since the interactive functionality requires using some kind of pointer (mouse or tap).

Non-interactive vizzes are a different story since their a11y requirements range from alt text to exposing raw tabular data, depending on what the purpose of the viz is.

I wonder if a good start could be defining more explicit use cases for visx[^2] and then documenting ways of making them accessible to all.

Is viz accessibility generally something that the visx team is planning of/interested in looking into? I'd be happy to help in some capacity, but since accessible vis isn't straightforward, the initiative would definitely require maintainer involvement.

Let me know and have a good weekend ahead!

[^1]: [Dots](https://airbnb.io/visx/dots), [Areas](https://airbnb.io/visx/areas), [BarStack](https://airbnb.io/visx/barstack), [Brush](https://airbnb.io/visx/brush), [XYChart](https://airbnb.io/visx/xychart), maybe more
[^2]: e.g. a concrete use case for [Areas](https://airbnb.io/visx/areas) could be to represent a value over time. Therefore, users may want to be able to get an understanding of the trend, explore specific points, or the like

**Comment by httpete** [comment]
I am interested in exactly this - and I will keep you posted on our progress here. We are following this guideline:

https://www.highcharts.com/blog/tutorials/10-guidelines-for-dataviz-accessibility/
