### ISSUE TITLE
Question regarding Status

### ISSUE THREAD

**Issue by elisechant** [hshoff/vx#156]
Regarding https://github.com/hshoff/vx#status - in particular: "Hold off on using this in production until I shake out some of the bigger API problems". 

Can you explain what this really means? Are you planning to do breaking refactoring changes? 

And then, what do you think the timeline to 1.0.0 will look like? 

If I can help you get there faster, I'd be happy to.

**Comment by hshoff** [comment]
Hi @elisechant, thanks for checking out vx and sure, happy to explain!

So we currently use vx in production at Airbnb. That's because we know and accept the risks that we might make some breaking api changes before v1. Also we want to make sure we can confidently say vx is production ready when we make the v1 announcement.

We don't currently have any breaking changes planned between now (v0.0.140) and v1. But until v1 is released, I worry about promising 0 breaking changes between now and then just to be safe. Trying to avoid too much churn which can fatigue developers and might turn them away from the project. 

The missing pieces for v1 are the big interactions. Brush, Zoom, Drag, etc which is my current focus right now. The other question everyone asks is about Animation. I haven't closed the [animation story issue](https://github.com/hshoff/vx/issues/6) yet, but I'm leaning towards leaving animation up to other react libraries and see where things go after React 16 lands. 

Once the interaction pieces have landed, the next step will to be finish docs and rests. 

And that brings us to v1 😄 

Hoping to get there soon! It's been a lot of fun so far. Contributions welcome!

**Comment by elisechant** [comment]
Ok cool, all makes sense. Thanks very much @hshoff.

**Comment by williaster** [comment]
gonna close this as v1 is coming 🔜
