### ISSUE TITLE
[text] fix <TextWrap />

### ISSUE THREAD

**Issue by hshoff** [hshoff/vx#16]
Make it easier to have text autowrap in svg. https://github.com/hshoff/vx/blob/master/packages/vx-text/src/text/TextWrap.js

**Comment by techniq** [comment]
I originally [created](https://github.com/recharts/recharts/pull/243) something like this for the recharts library (original [issue](https://github.com/recharts/recharts/issues/198)) but recently decided to extract it out into it's own repo/library as [react-svg-text](https://github.com/techniq/react-svg-text) mostly because I saw vx's `TextWrap` with it's TODO.

I haven't started using vx myself (yet), but thought you might want to use this.  It still needs some work before I release it on npm (see TODO section on README).  It also provides more features than just word wrapping (changing the `verticalAnchor` is very useful).  Check out the [demo](https://techniq.github.io/react-svg-text/) to get a feel for it.

**Comment by hshoff** [comment]
@techniq very nice! great work

**Comment by techniq** [comment]
@hshoff I release `react-svg-text` today - https://www.npmjs.com/package/react-svg-text.

I need to come up with a better testing strategy (see TODO section on README about jsdom / jest).  I also haven't done much through manually testing so hopefully I didn't miss anything to glaring.

Anyways, feel free to integrate this into `vx` as you see fit, and if you come across anything you need, feel free to submit a issue or PR.

**Comment by techniq** [comment]
fyi - I fired up a quick codepen and noticed I had forgot to add the `main` entry point in `package.json`.  I fixed this and pushed out `0.1.1`

**Comment by hshoff** [comment]
Awesome! thanks for this @techniq!

**Comment by techniq** [comment]
Very welcome. Thank you for vx :)

**Comment by hshoff** [comment]
fixed in: https://github.com/hshoff/vx/pull/208
