### ISSUE TITLE
Demo: Funnel Chart

### ISSUE THREAD

**Issue by msathis** [hshoff/vx#207]
If possible can you please add funnel chart to demo? I found a nice vizualization in dribbble for funnel chart https://dribbble.com/shots/2673159-Funnel-UI-concept

**Comment by msathis** [comment]
I gave it a try. But i couldn't create the exact curve as shown in the dribbble shot. @hshoff Any help would be appreciated. :)

**Comment by msathis** [comment]
Fixed it myself. It was not curve. Will share the chart soon :)

**Comment by hshoff** [comment]
Awesome! Excited to see the result.

**Comment by liviuignat** [comment]
Any news on the FunnelChart?

**Comment by psachs21** [comment]
@msathis yeah, i'd love to see an example.

**Comment by hshoff** [comment]
Thought I would take a swing at the dribbble example. Ideally instead of interpolating the data I should make a new curve function. But I got lazy.

![screen shot 2018-10-10 at 2 52 51 pm](https://user-images.githubusercontent.com/339208/46759129-8ef22b00-cc9c-11e8-865c-4729f23eed5d.png)
https://codesandbox.io/s/m46lkn49j

This was a fun one.

**Comment by liviuignat** [comment]
@hshoff  nice one. How would you do it vertical?

**Comment by cristinaITdeveloper** [comment]
@hshoff nice example, but unfortunately it doesn't works with 0.0.199 version of @vx/shape

**Comment by LuKaa** [comment]
Anybody skilled enough to rework the example to work with the latest @vx/shape version ?

**Comment by williaster** [comment]
here's a version updated with the latest
https://codesandbox.io/s/dazzling-chatterjee-kdisr?file=/src/index.tsx

**Comment by LuKaa** [comment]
@williaster You are a hero without a cape. Thank you!

**Comment by alexbu92** [comment]
I'm struggling extremely hard trying to add text ON TOP of this example, if I try to place any other element it'll move the graph down to make space for whatever I place, as if it were treating stuff as divs instead of following normal svg positioning which is absolute. Can any kind soul give me a pointer as to why this is?
