### ISSUE TITLE
Debounce option for ParentSize

### ISSUE THREAD

**Issue by Zaitsev** [hshoff/vx#228]
We used a high CPU-load math for render SVG  wrapped in Parentsize component, so it will be nice to debounce resize events, so SVG will be re-rendered after some timeout  after resize stopped

**Comment by williaster** [comment]
thanks for checking out vx Zaitsev! 

seems useful and similar to [similar functionality that exists within `withScreenSize` and `withParentSize](https://github.com/hshoff/vx/search?utf8=%E2%9C%93&q=lodash%2Fdebounce&type=)` (which we are [planning to deprecate](https://github.com/hshoff/vx/issues/220) for `v1` btw). 

PR's welcome :) but otherwise can get to it relatively soon 👍
