### ISSUE TITLE
Respect initial ordering Pie/Donut 

### ISSUE THREAD

**Issue by bernatfortet** [hshoff/vx#237]
When the values of a Pie/Donut change the pieces jump around. 
I've created a video to better explain what I mean:
https://www.dropbox.com/s/s5r0cnlobzuj531/donut.mov?dl=0

The expected behavior is that the positioning of the elements respects the input data.

Am I making sense?

(btw, I love @vx 👌  )

**Comment by hshoff** [comment]
Hi @bernatfortet, that's an awesome dashboard. Great work!

In this case you'll want to add a `pieSort` and sort on the index of the data. Looks like `d3-shape.pie` defaults the sort value by descending https://github.com/d3/d3-shape#pie_sortValues so that's why things are jumping around

Here's an example: https://codesandbox.io/s/13v7vowpy3
![vx-pie-sort](https://user-images.githubusercontent.com/339208/35479418-de2c104c-03ab-11e8-816d-406cf0e744f2.gif)

Looks like vx pie isn't exposing all of d3 pie methods as props, so I'll look into adding the rest of them in an upcoming release, but for now you should be able to get by with the `pieSort` prop which maps to d3's `pie.sort()`

**Comment by hshoff** [comment]
Going to close this for now. Happy to reopen if the above doesn't solve the problem.

**Comment by bernatfortet** [comment]
Hey @hshoff thank you so much for the late reply. It seems that pieSort works like a charm 👌 

Here I tried to animate that transition but it does very strange things haha
https://www.dropbox.com/s/lky9u45qqfwvyiw/transition.mov?dl=0

Anyway, animation is not need at this point. Thanks again!

**Comment by williaster** [comment]
Sometimes you'll need custom tween-ers to interpolate between states correctly. Not sure if that's the problem here without seeing a code snippet. [`react-move`](https://github.com/react-tools/react-move) should support custom tweening. Here's a donut chart [example](https://react-move.js.org/#/examples/charts).

**Comment by bernatfortet** [comment]
@williaster I was just using `.vx-pie-arc{ transition:500ms; }` to animate.
That react-move animation is very sexy!
