### ISSUE TITLE
Add label to <Bar />

### ISSUE THREAD

**Issue by petter-kaspersen** [hshoff/vx#251]
Hey!

How do I add a label to a <Bar /> element? In some charts you can use the ```centrum``` property to do that, but that doesn't work on the Bar. I have tried looking through the docs several times but I just can't seem to find out how to do it. 

Any help would be appreciated.

**Comment by williaster** [comment]
Hi @petter-kaspersen, thanks for checking out `vx`! 

Because `vx` is more of a "low-level" vis library like `d3`, there's no native support for labels out of the box with `<Bar />`. This enables maximum customization opportunities, and it's pretty easy to just add your own `<text />` element in conjunction with a `<Bar />` and maybe a `<Group />`. [This is a codepen](https://codesandbox.io/s/qx0kn2l794) to demonstrate and hopefully get you on track.

Also note the [`@vx/text` package](https://vx-demo.now.sh/text) which provides a lot of nice functionality for wrapping long labels etc. (this is not supported by default in `svg` `text` land, vs `html`-based text)

Preview
<img width="500" src="https://user-images.githubusercontent.com/4496521/36807108-e0dbfcd8-1c76-11e8-82e6-bd40069e9269.png" />

**Comment by hshoff** [comment]
haha @williaster beat me to the punch... but everything chris said plus here's another very similar example: https://codesandbox.io/s/zw2y6lrnzl
