### ISSUE TITLE
Arrows direction on the edges of the network graph

### ISSUE THREAD

**Issue by tinchoz49** [hshoff/vx#345]
Hi everyone!

Can it be possible to create arrows direction on the network graph?

Something like this one: http://bl.ocks.org/d3noob/5141278

Thanks, great library btw!

**Comment by hshoff** [comment]
Hi @tinchoz49, thanks for checking out vx. Yes this is possible through svg's [`<marker />`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/marker) element combined with a custom link component.

Here's an example: https://codesandbox.io/s/9qo1pqom9o

**Comment by tinchoz49** [comment]
wow thanks for the quick answer! It works great, I didn't know about the marker-(start|mid|end) attr.

**Comment by loopmode** [comment]
@tinchoz49 As long you can live with uniform markers, using the SVG marker attributes is the best way.
However, since you're referencing the markers via `id` and `url()`, having individual markers becomes difficult, and while it's more complicated, it's doable. Ping me if you face that issue at some point.
