### ISSUE TITLE
Bubble Chart from 3d.js

### ISSUE THREAD

**Issue by Groude** [hshoff/vx#377]
Hello!
Have you any plans to bringing **Bubble Chart** from _d3.js_ to this project?
Thank you.

**Comment by sto3psl** [comment]
Hi @Groude thanks for the issue. Can you specify what chart you mean and maybe add a picture? That would help a lot because vx can already do a lot of stuff.

From googling "d3 bubble chart"  I found this link https://beta.observablehq.com/@mbostock/d3-bubble-chart. Is that what you mean?

If so you can already do that with vx. It's part of `@vx/hierarchy` and called pack. Unfortunately it's not in the docs yet but you have an example in the gallery here https://vx-demo.now.sh/pack.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/5798652/47559400-ad4f5c00-d915-11e8-862d-d2698f048d29.png">

**Comment by hshoff** [comment]
Going to close this. Feel free to follow up here or open a new issue if you run into a blocker or question with your implementation.
