### ISSUE TITLE
Add className to parent group of LinePath

### ISSUE THREAD

**Issue by feerglas** [hshoff/vx#385]
If `LinePath` is used, a `path` is rendered inside a `<g>` element. It would be useful to pass a className which would be rendered on the `<g>` element. Some property like `groupClassName`would be nice.

A possible use-case would be the following: multiple `LinePath` are used inside a graph. The graph has a legend. If an item in the legend is hovered, the corresponding line in the graph should be highlighted by a specific color. In this case, the hovered line should have a higher z-index than the others. This is currently not possible.

**Comment by loopmode** [comment]
I've had a similar situation and used a somewhat valid workaround.
Have a look at https://stackoverflow.com/a/25302276/368254.
```
<use xlink:href="#one"/>
```
Using the `use` tag, you can create a "visual clone" of an element that has an ID. Now if you do that after the original element (e.g. further down in jsx), the clone is rendered on top.

So in my case, I made sure I always have an `id` - either the vx elements were rendered with an `id` prop, or I had a group around it just to have the `id`. 
Then when something was selected, I kept the selected ID in state, and when selected IDs were in state, I rendered the clones, entirely after the actual graph (separate `g`, sibling of the graph)
I think I had to apply `pointer-events: none` to the clones via CSS.

One drawback with such an approach is that you have to be careful with the IDs, so you don't have it in the DOM multiple times. 
So when I needed a smaller preview version of the entire graph (for zoom and pan), I passed down an addition instance name like "preview"and used it as a prefix for the IDs.

I must say this worked out pretty well, and it didn't feel like a waste of time.
But still, I agree that passing a `groupClassName` would be nice and save us troubles like what I described.

**Comment by hshoff** [comment]
This is fixed in https://github.com/hshoff/vx/pull/383 at https://github.com/hshoff/vx/blob/d3f1736282fdbb7d73dea2ddcd8eb8f0ad572f31/packages/vx-shape/src/shapes/LinePath.js#L34. Removed unnecessary `<g>` wrappers.

> the corresponding line in the graph should be highlighted by a specific color. In this case, the hovered line should have a higher z-index than the others. This is currently not possible.

Just a heads up on this use case -- unfortunately svg doesn't support `z-index`, it follows the painter's model. You can fake z-index by storing the render order in your react component's state then when you hover over your legend item you move that line to the end of the render order array. This is done in [https://vx-demo.now.sh/drag-i](https://vx-demo.now.sh/drag-i).

I haven't tried @loopmode's approach but sounds like it works.

**Comment by hshoff** [comment]
Closing as we removed unnecessary `<g>` wrappers in https://github.com/hshoff/vx/pull/383
