### ISSUE TITLE
Missing docs @vx/shape

### ISSUE THREAD

**Issue by visualcookie** [hshoff/vx#390]
Hello.

I've updated `@vx/shape` to `0.0.181` which currently breaks my build, since somehow a new prop has been introduced called `color` which is required. I've checked the docs and have found nothing at all about this prop.

How does this prop work and what does it do? To not break the build, I've set the prop to `color={() => false}` which makes all my bars black.

**Comment by visualcookie** [comment]
Update: I've rechecked your commit messages and it seems that the `color` prop was `zScale` before. That solves the case.

Maybe it should be added to the docs.

**Comment by hshoff** [comment]
There were a number of breaking changes of v0.0.181. While the docs a bit behind due to all of the updates we have other resources that are up to date.

- For a summary, motivation, and before + after of changes please see: [https://github.com/hshoff/vx/pull/383](https://github.com/hshoff/vx/pull/383)
- v0.0.181 [changelog](https://github.com/hshoff/vx/blob/master/CHANGELOG.md#v00181)
-  all [gallery](https://vx-demo.now.sh/gallery) examples are up-to-date and using v0.0.181. Here's an example of a BarGroup that uses the color prop, a tooltip, and onMouseMove/onMouseOut: https://vx-demo.now.sh/bargroup

**Comment by visualcookie** [comment]
> There were a number of breaking changes of v0.0.181. While the docs a bit behind due to all of the updates we have other resources that are up to date.
> 
>     * For a summary, motivation, and before + after of changes please see: #383
> 
>     * v0.0.181 [changelog](https://github.com/hshoff/vx/blob/master/CHANGELOG.md#v00181)
> 
>     * all [gallery](https://vx-demo.now.sh/gallery) examples are up-to-date and using v0.0.181. Here's an example of a BarGroup that uses the color prop, a tooltip, and onMouseMove/onMouseOut: [vx-demo.now.sh/bargroup](https://vx-demo.now.sh/bargroup)

Thanks for the quick reply. Have already checked the first two links out. Looked over the gallery examples just now and on the BarGroup there's no example for the tooltip, but for an `onClick`.

After the update I was not able to get it working with `onMouseMove/onMouseOut`. Maybe my BarGroup is not correctly defined? Got no errors in console tho.

```
<BarGroup
  data={data}
  keys={keys}
  height={yMax}
  x0={x0}
  x0Scale={x0Scale}
  x1Scale={x1Scale}
  yScale={yScale}
  color={color}
  rx={4}
  onMouseMove={x => event => {
    this.handleTooltip(event, x)
  }}
  onMouseOut={() => hideTooltip}
/>
```

**Comment by visualcookie** [comment]
Oh, so I need to do that extra `<rect />` and can't apply it on the `<BarGroup />` component anymore?

**Comment by visualcookie** [comment]
@hshoff Thanks for the headsup there. Going to update the version now and applying all the breaking changes to make it work again.
