### ISSUE TITLE
@vx/responsive triggers a loop

### ISSUE THREAD

**Issue by niwsa** [hshoff/vx#441]
I am trying to use the @vx/responsive to render a Area chart but can't quite get it right.Whatever I try it goes into a loop increasing the height continously.

Here is the sandbox [![Edit k0r7rr1n5](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k0r7rr1n5?fontsize=14)

**Comment by hshoff** [comment]
Hi @niwsa, here's a fork of your sandbox without the loop: https://codesandbox.io/s/zq8q13wj0m

The quick fix is to add `min-height: 0px;` to the parent div that contains the `<ParentSize>` component. You're seeing an indefinite loop because the parent div doesn't have a height on it and instead is a flex container that will grow based on the content dimensions. The problem is the content dimensions is based on the parent div dimensions so it's updating the parent which triggers the content to update.

**Comment by niwsa** [comment]
Thanks @hshoff that works :+1:

**Comment by Tatamethues** [comment]
THANKS!!!!!!!!!!!!!!!!!!!!!
