### ISSUE TITLE
@vx/shape: "^0.0.189" and viewsource code

### ISSUE THREAD

**Issue by kang-chen** [hshoff/vx#469]
Hi, nice one with VX. Been looking at your viewsource demos: https://viewsource.now.sh/bitcoin  the graph doesn't show when using @vx/shape: "^0.0.189" all seems fine when using @vx/shape: "0.0.131".

I can submit a PR if I find what it is although thought I'd submit this issue also.

**Comment by hshoff** [comment]
Hi, thanks for checking out vx and viewsource. Yes, there have been some breaking changes to vx since making the viewsource demos. This issue is more applicable to: https://github.com/hshoff/viewsource so going to close this here and we can follow up in the viewsource repo. 

Breaking changes can be found in the changelog here: https://github.com/hshoff/vx/blob/master/CHANGELOG.md

A summary of the biggest breaking change can be found here: https://github.com/hshoff/vx/pull/383
