### ISSUE TITLE
How to implement tooltip in functional component?

### ISSUE THREAD

**Issue by laneherby** [hshoff/vx#555]
How can I implement tooltip in a functional component. The demo only shows class based components.

**Comment by hshoff** [comment]
For now you would use the HOC and class component. We're focused on TypeScript migration at the moment, hooks are coming after.

**Comment by MavenOfCode** [comment]
Hi,
 I think I tried the above using another example from an early issue elsewhere in the repo and it turns out that as of this release (0.0.181) the tooltip stops showing on the Bar shape for some reason. I am still a newbie and not savvy enough to know why, but I tested each version of dependency until tooltip stopped working and it is this version. 
Here is the CodeSandbox with a working tooltip with @vx/shape at 0.0.179. (also it generates a console error, but I don't know if that is my fault)
https://codesandbox.io/s/vx-responsive-tooltip-version-check-8s6kl
Hope this is helpful.

**Comment by hshoff** [comment]
The demo here shows how to use `withTooltip()` and a functional component: https://vx-demo.now.sh/areas
and there is an example for `useTooltip()` here: https://codesandbox.io/s/github/hshoff/vx/tree/master/packages/vx-demo/src/sandboxes/vx-tooltip?file=/Example.tsx
