### ISSUE TITLE
BarGroupHorizontal expects an inverse x scale?

### ISSUE THREAD

**Issue by diagramatics** [hshoff/vx#573]
Hey folks! I find it odd that `BarGroupHorizontal` expects an inversed x scale (passing in `.range([xMax, 0])` as opposed to `.range([0, xMax])`) even though the chart itself isn't supposed to be rendered right to left.

To demonstrate with the demo in https://vx-demo.now.sh/bargrouphorizontal, if I use a bottom axis such as:

```jsx
<AxisBottom
  top={yMax}
  left={0}
  scale={xScale}
  stroke="#e5fd3d"
  tickStroke="#e5fd3d"
  tickLabelProps={() => ({
    fill: '#e5fd3d',
    fontSize: 11,
    textAnchor: 'middle',
    dy: '0.33em',
  })}
/>
```

The axis will be rendered backwards:
![image](https://user-images.githubusercontent.com/5153378/71672924-58d22700-2dcb-11ea-8b35-db8afe2ae413.png)

This seems unintuitive to me where you have to take the same scale and invert it just to accomodate the axis, and even potentially with markers as well.

This is caused by the line in:
https://github.com/hshoff/vx/blob/51f5cc3cfa12db6eb1703aceba1e204b19ca505d/packages/vx-shape/src/shapes/BarGroupHorizontal.tsx#L66

If you agree that the inversion based on width is unnecessary I'm happy to make a PR and fix it.

**Comment by williaster** [comment]
Hey @diagramatics! Thanks for checking out `vx` and reporting this 🙏 

I agree this is unintuitive and not the right behavior, it's also inconsistent with the expected scale configuration for the [`BarStackHorizontal` `xScale`](https://github.com/hshoff/vx/blob/master/packages/vx-demo/src/components/tiles/barstackhorizontal.js#L75) which is **not inverted**. I would guess that this ended up happening when the (vertical) `BarGroup` (which has a standard inverted y-axis due to the SVG coord system) was modified for horizontal use. 

If you would be open to helping fix it, we would happily welcome a PR!
