### ISSUE TITLE
overlapping Nodes in Link Types.

### ISSUE THREAD

**Issue by Scharaa** [hshoff/vx#607]
I have used the link Types example in my code. The Problem that I have is that my tree has too many nodes on each level and they over lap. Is there anyway that I can avoid it?

**Comment by williaster** [comment]
Hi @Scharaa 👋 thanks for checking out `vx`! It's hard to tell exactly what you are describing without a screenshot or a codesandbox link, but my interpretation is that this is a limitation of the underlying `d3` algorithm, and nothing to do with `vx`. Basically any graph or tree layout will become more and more dense with more nodes and ultimately they may overlap without special algorithm treatment (i.e., not out-of-the-box).

You might try tweaking some of the [`separation` hooks](https://github.com/d3/d3-hierarchy#tree_separation) available in the underlying `d3-hierarchy`, or consider a radial layout vs linear as the former can handle more density in some cases, etc.

**Comment by Scharaa** [comment]
I guess that was the problem. thank you :)

**Comment by techniq** [comment]
@Scharaa I forgot to reply earlier, but I've also had success using [nodeSize](https://github.com/d3/d3-hierarchy#tree_nodeSize) as well for some visuals.

Instead of specifying [tree size](https://github.com/d3/d3-hierarchy#tree_size) and having the nodes fit within this bounding box, you can use `nodeSize` and have the tree size dynamic.  Mixed with [zooming / panning](https://vx-demo.now.sh/zoom-i), this has worked well for us with up to 3000 nodes (at various levels on the hierarchy).

Tweaking `separation` also helps with getting the desired result.
