### ISSUE TITLE
Few points, disaligns Area graph

### ISSUE THREAD

**Issue by eduhenke** [hshoff/vx#665]
The Area graph just seems to disalign, when there's few points(e.g. less than 10)

![image](https://user-images.githubusercontent.com/8304447/79417156-a2fca400-7f87-11ea-9cd9-f21a2e448191.png)

I can't directly copy from my code, so I'm just going to give a small sample of what I'm doing:

```typescript
const xMax = parentWidth! - margin.left - margin.right;
const yMax = parentHeight! - margin.top - margin.bottom;
  
const xScale = scaleBand({
  rangeRound: [0, xMax],
  domain: data.map(x),
  padding: 0,
});
const yScale = scaleLinear<number>({
  rangeRound: [yMax, 0],
  domain: [0, Math.max(...data.map(y).map(y => y.valueOf()))],
 });
return (
  <svg width={parentWidth} height={parentHeight}>
    <Group top={margin.top} left={margin.left}>
      <AreaClosed
        data={data}
        yScale={yScale}
        x={xPoint}
        y={yPoint}
        fillOpacity={1}
        fill={`url(#gradient`}
        stroke={""}
        curve={curveMonotoneX}
      />
   </Group>
 </svg>
);

**Comment by hshoff** [comment]
Hi, that's a nice looking chart, great work!

Looks like your x scale is `scaleBand`  which is likely where the misalignment is coming from. There are probably always misaligned it's just when there are less points that it becomes more noticeable. 

I would try adding an offset of something like`xPoint + xScale.bandwidth() / 2` to align the points with the bottom axis. 

is it possible to use a linear scale instead of band? 

More info:
- https://github.com/d3/d3-scale#band-scales
- https://observablehq.com/@d3/band-align

**Comment by williaster** [comment]
Hard to debug this without a codesandbox / fully reproducible example, but if the band <> linear trick doesn't work, another thought might be  invalid/undefined `y` value from `72/4` and on, which would result in a break between points and the shape that you see. could that be the case?

you can see the [`d3` `.defined()` docs](https://github.com/d3/d3-shape#line_y) for more about this.
