### ISSUE TITLE
Tooltip Positioning Issue in Functional Components

### ISSUE THREAD

**Issue by ahmetuysal** [hshoff/vx#675]
Hi, I am using vx for a project and spent several hours trying to correctly position a tooltip. In [the sandbox provided in the docs](https://codesandbox.io/s/kw02m019mr?file=/src/index.js) its says that `withTooltip` wraps the component in a `<div style="position: relative" />`. 

I think we should also manually do this for FunctionalComponents when using `useTooltip` (this is how I solved my positioning issue). If this is the case, can you please add a clear explanation to the docs?

Thank you for your amazing work!

**Comment by williaster** [comment]
@ahmetuysal 👋 , thanks for checking out `vx`. Ah yes, this is nuanced and should probably be added to get people going more quickly. I'd like to add a tooltip-only demo soon for the v1 release, in the meantime we could probably add this to the readme to get most of the way there?

PRs, welcome, otherwise I'll probably add it when adding a tooltip demo 👍

**Comment by ahmetuysal** [comment]
Sure, I will add it and open a pull request :)

**Comment by ahmetuysal** [comment]
Ah, you already opened a PR, thanks :)
