### ISSUE TITLE
Opacity-related attributes for svg objects

### ISSUE THREAD

**Issue by jacek213** [hshoff/vx#71]
SVG objects support properties such as:

* `fill-opacity`
* `stroke-opacity`
* `opacity`

Would be nice to support them - useful especially in transitions.

**Comment by hshoff** [comment]
I need to do a consistency pass on `@vx/shape`. Likely will do the pass at the same time as https://github.com/hshoff/vx/issues/69. Here's how each shape should support all SVG attributes: https://github.com/hshoff/vx/blob/master/packages/vx-shape/src/shapes/Line.js#L28

A quick pass through `@vx/shape` shows it's just `<LinePath />` missing the rest props pass through. 

I'll get this fixed in `v0.0.120`

**Comment by jacek213** [comment]
Thanks for a quick reply, this solution looks solid :)

I think `circle` used inside `GlyphDot` should get the `restProps`: https://github.com/hshoff/vx/blob/master/packages/vx-glyph/src/glyphs/Dot.js
