### ISSUE TITLE
groupScale and findNearestDatum in Sandpit example

### ISSUE THREAD

**Issue by alangrn** [hshoff/vx#798]
In the sandpit example which has various chart options in the Group.tsx file there is a comment above findNearestDatum. That TODO is refactor as memoized. Is there any plan to do this or is there an updated example somewhere else?

**Comment by williaster** [comment]
Hi @alangrn 👋  thanks for checking out `vx`. Can you provide a link to the example you're referring to? There are dozens of sandbox examples linked to from the demo site.

**Comment by alangrn** [comment]
HI @williaster. I have been using this link. Does not seem to load at the moment so let me know if I need to find another link for this.

https://codesandbox.io/s/github/hshoff/vx/tree/chris--xychart-poc/packages/vx-demo/src/sandboxes/vx-chart-poc?file=/src/components/series/Group.tsx:0-6530

**Comment by williaster** [comment]
Ohhh, I see. I would take that example with a grain of salt since the PR is a proof-of-concept and will not be merged. I may close it to clarify that.

Actual progress on the new `xychart` package is being [tracked here](https://github.com/hshoff/vx/projects/3), and `Group` has not been implemented yet.
