### ISSUE TITLE
Should quartiles in vx/boxplot be switched?

### ISSUE THREAD

**Issue by trainorpj** [hshoff/vx#98]
[`vx/boxplot`](https://github.com/hshoff/vx/tree/master/packages/vx-boxplot) requires `firstQuartile` and `thirdQuartile` to render the boxplot.  

From my understanding of summary statistics, the standard order of the values should be: 

`min < firstQuartile < median < thirdQuartile < max`

Currently, `vx/boxplot` renders the box when: 

`min < thirdQuartile < median < firstQuartile < max`

Should `vx/boxplot` follow the first or the second ordering?

[See this sandbox for an implementation](https://codesandbox.io/s/jRYy37Xn5)

<img width="370" alt="screen shot 2017-07-15 at 1 29 24 pm" src="https://user-images.githubusercontent.com/13276704/28241408-d7d8afe6-6961-11e7-87fc-ee9ad3068451.png">
<img width="497" alt="screen shot 2017-07-15 at 1 29 08 pm" src="https://user-images.githubusercontent.com/13276704/28241405-cf320612-6961-11e7-8b02-aeddd6c37f05.png">

**Comment by hshoff** [comment]
Hi @trainorpj thanks for checking out vx and for the helpful example code!

Here's an updated take on your example: https://codesandbox.io/s/v25Vm3Q15

<img width="371" alt="screen shot 2017-07-16 at 9 28 41 pm" src="https://user-images.githubusercontent.com/339208/28255593-d00951e6-6a6d-11e7-91a3-0b7196d5f231.png">

`@vx/boxplot` expects the y axis to increase in value pointing up, which means it always expects max to be the top line. Looks like you're trying to draw an inverted box plot, which the current `@vx/boxplot` doesn't allow at the moment. This is because when boxplot goes to draw the box it draws a `rect` region starting at `y={thirdQuartile}` with `height={firstQuartile - thirdQuartile}`.  Your first screenshot doesn't show a box because `height={-170}` in that example. The solution here is to pass in scaled values starting with max at the top and min on the bottom. 

So the current `@vx/boxplot` api expects scaled values where the y axis increases going towards the top of your screen. We should make it so it can support the inverted case where y axis increases going towards the bottom of your screen to.

Hope that helps and thanks for opening up the issue for clarification. We will look into adding this in an upcoming release.

**Comment by trainorpj** [comment]
Thanks @hshoff for taking the time to respond! This makes a lot of sense, especially if you're making reusable charts with svg-coordinates in mind :grin:
